from datetime import datetime, timezone
from pathlib import Path

from kirobi_core.audit import AuditLogger
from kirobi_core.autonomous import in_quiet_hours, run_loop, run_once


def _seed(repo: Path) -> None:
    (repo / "README.md").write_text("hi", encoding="utf-8")
    (repo / "kirobi_core").mkdir()
    (repo / "kirobi_core" / "x.py").write_text("x = 1\n", encoding="utf-8")
    (repo / "metadata").mkdir()
    (repo / "metadata" / "AGENTREGISTRY.md").write_text(
        """## 1. kirobi-coder
**Rolle:** Coder
**Modell:** qwen2.5-coder:32b
**Zone-Zugriff:** PUBLIC, WORKSPACE
""",
        encoding="utf-8",
    )


def test_run_once_is_dry_run_by_default(tmp_path):
    _seed(tmp_path)
    audit = AuditLogger(tmp_path / "events.log")
    report = run_once(tmp_path, audit=audit, write_report=False)
    assert report.dry_run is True
    assert report.scan_summary["total_files"] >= 3
    # No files should have been created besides the audit log.
    assert not (tmp_path / "AUTOGENERATED.md").exists()


def test_run_once_writes_report_when_requested(tmp_path):
    _seed(tmp_path)
    report = run_once(tmp_path, write_report=True)
    reports_dir = tmp_path / ".kirobi" / "reports"
    files = list(reports_dir.glob("autonomous-*.json"))
    assert files, "expected at least one report file"
    assert report.tasks  # backlog should not be empty


def test_in_quiet_hours_handles_midnight_wrap():
    # 23:30 should fall inside 22:00-07:00
    now = datetime(2026, 5, 5, 23, 30, tzinfo=timezone.utc)
    assert in_quiet_hours(now, "22:00-07:00") is True
    # 12:00 should not.
    midday = datetime(2026, 5, 5, 12, 0, tzinfo=timezone.utc)
    assert in_quiet_hours(midday, "22:00-07:00") is False


def test_in_quiet_hours_empty_spec_is_false():
    now = datetime(2026, 5, 5, 23, 30, tzinfo=timezone.utc)
    assert in_quiet_hours(now, "") is False
    assert in_quiet_hours(now, "garbage") is False


def test_run_loop_respects_iteration_count(tmp_path):
    _seed(tmp_path)
    sleeps: list[float] = []
    reports = run_loop(
        tmp_path,
        interval_seconds=0,
        iterations=2,
        sleep_fn=sleeps.append,
    )
    assert len(reports) == 2


def test_run_loop_skips_during_quiet_hours(tmp_path):
    _seed(tmp_path)
    fixed_now = datetime(2026, 5, 5, 23, 30, tzinfo=timezone.utc)
    reports = run_loop(
        tmp_path,
        interval_seconds=0,
        iterations=1,
        quiet_hours="22:00-07:00",
        now_fn=lambda: fixed_now,
        sleep_fn=lambda _s: None,
    )
    assert reports == []
